class Strings:
    ADD_NOTE = '\nСоздание заметки:'
    DELETE_NOTE = '\nУдаление заметки:'
    EDIT_NOTE = '\nРедактирование заметки:'
    VIEW_NOTES = '\nПросмотр заметок:'
    SAVE_NOTES = '\nСохранение заметок в файл:'
    UNKNOWN_FORMAT = 'Неизвестный формат файла: '
    NOTES_SAVED = 'Заметки успешно сохранены в файл.'
    NO_NOTES = 'Нет заметок для показа.'
    INCORRECT_CHOICE = 'Некорректный выбор. Попробуйте еще раз.'
    UNKNOWN_DATE_FORMAT = 'Неверный формат даты!'